### PR TITLE
[ADD] [11.0] Added filters to br_account, br_purchase, br_sale module

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
Hi @danimaribeiro ,

Can you check the travis error? I think there are the same error that happened in https://github.com/Trust-Code/odoo-brasil/pull/520. My local database passes the test.

Thanks!

**Comment by danimaribeiro** [comment]
@svazquezco 
Cherry-pick this commit to fix the problem.
https://github.com/Trust-Code/odoo-brasil/commit/4a6a660d67b914f79d441f4ee7a9c8bf92594e61

**Comment by ghost** [comment]
Thanks @danimaribeiro ! I've done the cherry-pick but test doesn't pass. 

I've already done the filtering of br_purchase and br_sale modules, I'll merge in this branch and then I'll update this branch with all the changes made in 11.0. 

Maybe this solve the problem.

**Comment by ghost** [comment]
@danimaribeiro , can you merge this pull? 
Thanks!!

**Pull request merged**
