### PR TITLE
[11.0] br_localization_filtering

### PR DESCRIPTION
**Pull request by ghost**
**TODO:**
- br_base:
-- ~~res_company.py~~
-- ~~res_bank.py~~
-- ~~res_partner.py~~

### CODE REVIEW

**Comment by ghost** [comment]
Hi @danimaribeiro,

**EDIT: You can discard this comment, it's solved!**  
**EDIT2: I don't why but the problem still happening**

I have two errors in Travis that I don't know who to solve them because I think this had nothing to do with field refactoring.

The first one is related to currency_code, the parser file get "brl"  (lower case) instead of "BRL" (upper case):

```
ERROR: test_import_ofx_default (odoo.addons.br_bank_statement_import.tests.test_import_statement.TestImportStatement)
Traceback (most recent call last):
`   File "/home/travis/build/Trust-Code/odoo-brasil/br_bank_statement_import/tests/test_import_statement.py", line 40, in test_import_ofx_default
`     self.import_ofx.import_file()
`   File "/home/travis/odoo-11.0/addons/account_bank_statement_import/account_bank_statement_import.py", line 41, in import_file
`     currency, journal = self._find_additional_data(currency_code, account_number)
`   File "/home/travis/odoo-11.0/addons/account_bank_statement_import/account_bank_statement_import.py", line 138, in _find_additional_data
`     raise UserError(_("No currency found matching '%s'.") % currency_code)
` odoo.exceptions.UserError: ("No currency found matching 'brl'.", '')
ERROR: test_import_ofx_itau (odoo.addons.br_bank_statement_import.tests.test_import_statement.TestImportStatement)
Traceback (most recent call last):
`   File "/home/travis/build/Trust-Code/odoo-brasil/br_bank_statement_import/tests/test_import_statement.py", line 77, in test_import_ofx_itau
`     self.import_ofx.import_file()
`   File "/home/travis/odoo-11.0/addons/account_bank_statement_import/account_bank_statement_import.py", line 41, in import_file
`     currency, journal = self._find_additional_data(currency_code, account_number)
`   File "/home/travis/odoo-11.0/addons/account_bank_statement_import/account_bank_statement_import.py", line 138, in _find_additional_data
`     raise UserError(_("No currency found matching '%s'.") % currency_code)
` odoo.exceptions.UserError: ("No currency found matching 'brl'.", '')
```

The second one is about duplicated key:

```
ERROR
ERROR: test_ie_duplicated (odoo.addons.br_base.tests.test_base.TestBase)
Traceback (most recent call last):
`   File "/home/travis/build/Trust-Code/odoo-brasil/br_base/tests/test_base.py", line 102, in test_ie_duplicated
`     self.env['res.partner'].create(vals)
`   File "/home/travis/odoo-11.0/odoo/addons/base/res/res_partner.py", line 534, in create
`     partner = super(Partner, self).create(vals)
`   File "/home/travis/odoo-11.0/addons/mail/models/mail_thread.py", line 236, in create
`     thread = super(MailThread, self).create(values)
`   File "/home/travis/odoo-11.0/odoo/models.py", line 3373, in create
`     record = self.browse(self._create(old_vals))
`   File "/home/travis/odoo-11.0/odoo/models.py", line 3520, in _create
`     field.write(self.with_context(rel_context), vals[name], create=True)
`   File "/home/travis/odoo-11.0/odoo/fields.py", line 2259, in write
`     comodel.create(act[2])
`   File "/home/travis/odoo-11.0/addons/mail/models/mail_followers.py", line 126, in create
`     res = super(Followers, self).create(vals)
`   File "/home/travis/odoo-11.0/odoo/models.py", line 3373, in create
`     record = self.browse(self._create(old_vals))
`   File "/home/travis/odoo-11.0/odoo/models.py", line 3466, in _create
`     cr.execute(query, tuple(u[2] for u in updates if len(u) > 2))
`   File "/home/travis/odoo-11.0/odoo/sql_db.py", line 155, in wrapper
`     return f(self, *args, **kwargs)
`   File "/home/travis/odoo-11.0/odoo/sql_db.py", line 232, in execute
`     res = self._obj.execute(query, params)
` psycopg2.IntegrityError: duplicate key value violates unique constraint "mail_followers_mail_followers_res_partner_res_model_id_uniq"
` DETAIL:  Key (res_model, res_id, partner_id)=(res.partner, 53, 3) already exists.
```

I've compared failed test with this -> https://travis-ci.org/Trust-Code/odoo-brasil/builds/389668999

I've seen that br_base is not installed:

Pass test:
image

Failed test:
image

It seems that test broken when br_localization_filtering is added.

Thanks for your help!!

**Comment by ghost** [comment]
@danimaribeiro, I've finished br_base module refactoring, can you help me with previous comment?

Thanks!

**Comment by danimaribeiro** [comment]
@svazquezco The first one was related to the order the tests were executing, I made sure br_bank_statement_import executes after br_base, because here I activate the currency:
https://github.com/Trust-Code/odoo-brasil/blob/11.0/br_data_base/data/br_base_data.xml#L5
Without the new module br_base always executed first, not sure why it changed.

Second one got lucky, I don't know exactly why but create of Odoo was updating vals variable, and I think create was setting id to vals.
I made a explicit copy of vals, and I use the copies to create, it solved the problem.
Also interesting is that in my machine it does not occur, just in build (maybe related to py 3.5 and 3.6?)

**Comment by ghost** [comment]
Thanks @danimaribeiro!!
About first one, I think adding the dependency to br_base changes the order of the modules. 
Anyway, neither of them fails in my machine with python 3.6 so maybe this is the problem.

**Pull request merged**
